# Site settings
title: "Alexa Kelley Resume 2024"
description: "Alexa Kelley's Resume 2024"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alexa​ (StarChild) Kelley"
resume_title:                   "Former security manager at VRChat"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "starchild@chaos-cat.page"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 (734) 644-1965"
#resume_contact_address:         "Relocating"

resume_header_contact_info:     "+1 (734) 644-1965 • starchild@chaos-cat.page"
display_header_contact_info:    "false"

resume_header_intro: "<p> I am a security professional with a diverse array of skills, including security operations, vulnerability management, people management, cloud architecture, data analysis, threat modelling, and cyber intelligence. I strive for continuous improvement, heavily influenced by the principles of servant leadership. I excel both as a leader—empowering my team to succeed—and as an individual contributor (IC) engineer, hardening an organisation against threats.
<br>
My professional philosophies include:

  <ul> 
<li> Treat people with dignity and respect.</li>
<li> Designing systems with a people-first approach.</li>
<li> Prioritising sustainable design and implementation for long-term success.</li>
<li> Focusing on techniques and concepts over tools, i.e., adopting a tool-agnostic approach wherever possible.</li>
  </ul>
</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_languages:       true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
#resume_section_education:       true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/PurpleStarChild"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/alexa-kelley/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://chaos-cat.page"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
